forge.go

Changing the current working directory conflicts with puppetfile mode. As the working directory is not set back after all modules are downloaded, the `syncForgeToModuleDir()` function will move them to _cache_tmp_dir/$module_dir_, and not to _./$module_dir_ as expected.
Either the current working directory must be set back after the tar file is extracted, which proves to be rather complicated as all modules are processed asynchronously, and therefore could only be done in a place not related to the actual change of the working directory.
As it is better to not change the current working directory at all the operations for the extracted files and directories should include the absolute path for the target file, as implemented by this patch.
Not sure if this is the correct branch to submit …

remove change of current working directory

---

forge.go
g10k.go
helper.go

This will use `mv` instead of hardlinks to populate the Puppet environment with Puppetlabs Forge modules.
This also means that the cachedir needs to get deleted afterwards.
Also added `cachedir` env variable to specify a different cachedir than
the default `/tmp/g10k/`
This fixes #10

add -usemove param

---

config.go
forge.go
g10k.go
helper.go
puppetfile.go

- replaced ugly regex parsing of the Forge JSON response with real JSON decoding
- adding meta information (like which Forge base URL should be used) about every Forge module to all functions

add custom Forge base URL support in Puppetfile

---

README.md
config.go
g10k.go
g10k_puppetfile_test.go
g10k_test.go
helper.go
puppetfile.go
test.yaml
tests/TestConfigForceForgeVersions.yaml
tests/TestFallbackPuppetfile
tests/TestForceForgeVersionsPuppetfile
tests/TestForceForgeVersionsPuppetfileCorrect
tests/TestReadPuppetfile
tests/TestReadPuppetfileConflictingGitAttributesBranch
tests/TestReadPuppetfileConflictingGitAttributesCommit
tests/TestReadPuppetfileConflictingGitAttributesLink
tests/TestReadPuppetfileConflictingGitAttributesRef
tests/TestReadPuppetfileConflictingGitAttributesTag
tests/TestReadPuppetfileDuplicateForgeModule
tests/TestReadPuppetfileDuplicateGitAttribute
tests/TestReadPuppetfileForgeCacheTtl
tests/TestReadPuppetfileIgnoreUnreachable
tests/TestReadPuppetfileIncompatibleGitAttributesTag
tests/TestReadPuppetfileInvalidForgeModuleName
tests/TestReadPuppetfileLink
tests/TestReadPuppetfileMissingGitAttribute
tests/TestReadPuppetfileTooManyGitAttributes
tests/TestReadPuppetfileTrailingComma

you can enforce version numbers of Forge modules in your Puppetfiles instead of `:latest` or `:present` by adding `force_forge_versions: true` to the g10k config in the specific resource
```
---
:cachedir: '/tmp/g10k'
sources:
example:
remote: 'https://github.com/xorpaul/g10k-environment.git'
basedir: '/tmp/example/'
force_forge_versions: true
```
If g10k then encounters `:latest` or `:present` for a Forge module it errors out with:
>2016/11/15 18:45:38 Error: Found present setting for forge module in /tmp/example/example_benchmark/Puppetfile for module puppetlabs/concat line: mod 'puppetlabs/concat' and force_forge_versions is set to true! Please specify a version (e.g. '2.3.0')

add force_forge_versions source parameter to g10k config

---

git.go

The execution in a subshell and not quoting the branch name results in arbitrary remote code execution being possible.
Steps to reproduce:
* Push a branch with a name with shell code: `git checkout -b 'master;whoami' && git push -u origin`
* Synchronize or wait for synchronization
If an interface to g10k is available no push is needed in the first place, the code can be pushed directly.
Fix is quoting the branch for the subshell to prevent interpretation by the shell.

Fix remote arbitrary code execution

---

git.go

Log fails under weird circumstances and causes empty directories for
modules without the branch, even though ignore-unreachable is set.
@xorpaul  You fixed that before, but it wasn't pushed to github.

Determine existing ref with rev-parse instead of log

---

forge.go

This change made `go build` pass on my Mac. Before that I got same errors as in https://github.com/xorpaul/g10k/issues/56 , so I guess that this will also fix Windows builds.
PS These are my first shots at golang, so please don't be harsh. :)

Fix build on Mac (and possibly Windows)

---

README.md
config.go
forge.go
g10k.go
g10k_test.go
git.go

this will allow users to specify how many Goroutines are allowed to run in parallel for Git and Forge module resolving
Replaces #39

add -maxworker parameter to limit parallel Goroutines

---

helper.go

This helps grabbing error messages when calling g10k from a script or wrapper tool.

Print fatal errors to stderr instead of stdout

---

git.go

`git rev-parse --verify` would not throw an error if the input "looks"
like a commit id, e.g. it is 40 hexadecimal characters. Therefore, check
that `git archive` exited with no errors.

More robust git failure detection

---

forge.go

Without this patch modules from forge are constantly purged with:
```
Need to purge ./modules/firewall, because it exists without a metadata.json. This shouldn't happen!
```
Because of the missing `/` between the `targetDir` and `metadata.json`.

Add missing trailing / to targetDir

---

README.md
g10k.go
g10k_test.go
puppetfile.go

I have a project where I want to deploy tagged builds puppet resources without ending up loads of environments. So I've added the ability include tags as well as branches.
I've also added the ability to rename the output folder. My intention is to get a specific tag using the -branch option and then renaming it to a name. E.g. tag 1.0.0 renamed to production.

Added tag and rename output option

---

config.go
g10k.go
helper.go

Hi,
we are currently investigating a method to validate a given Puppetfile even before a sync is actually triggered and I wondered if you could incorporate such a functionality in g10k.
I build a example implementation of this feature, so it's clearer what I want to achieve. The added '-validate' flag forces the program to exit right after it parsed a given config or Puppetfile and prints all errors that it collected during the process. The exit code is 1 in case something went wrong, and 0 if the file was parsed without a problem.
greetings
Phillip

Puppetfile validation

---

g10k.go
helper.go

Fixes: #136 
I was getting some confusing segfaults when the ownership of the g10k CacheDir was wrong.
The program should print an error instead of segfaulting.  I'm hoping this change does the trick, but I've never written in Golang before.

Check writability of configured CacheDir.

---

git.go

It seems that since it has been implemented, maxworker does not work correctly.
The main reason is that the  `done` channel is filled outside of the go loop which spawn the func : https://github.com/xorpaul/g10k/blob/master/git.go#L88 
Moving it to the end of the goroutine makes maxworker work correctly.

Really respect `maxworker` parameter during git clone/remote update, close #140

---

g10k.go
g10k_test.go
puppetfile.go
tests/TestConfigFullworkingBranchFilter.yaml
tests/TestConfigFullworkingBranchFilterRegex.yaml
tests/branch_filter_command.sh

added source settings in the g10k config yaml to filter out Puppet environments / control repository branches based on generic commands via `filter_command` or simply via Golang compatible regex `filter_regex`
Examples:
```
==> tests/TestConfigFullworkingBranchFilter.yaml <==
---
:cachedir: '/tmp/g10k'
sources:
full:
remote: 'https://github.com/xorpaul/g10k-fullworking-env.git'
basedir: '/tmp/branchfilter'
filter_command: 'tests/branch_filter_command.sh $R10K_BRANCH ^(single|master)$'
```
```
==> tests/TestConfigFullworkingBranchFilterRegex.yaml <==
---
:cachedir: '/tmp/g10k'
sources:
full:
remote: 'https://github.com/xorpaul/g10k-fullworking-env.git'
basedir: '/tmp/branchfilter'
filter_regex: '^(single|master)$'
```

add branch filtering

---

.gitignore
.travis.yml
Dockerfile
Makefile
build_release.sh
g10k.go
g10k_test.go
git.go

The command ssh-add without -K will always generate a password prompt for each git repository. To avoid it you should use -K. So ssh-add will use OS X Keychain

Use ssh-add -K (Keychain) for Mac OS X

---

README.md
config.go
g10k.go
g10k_puppetfile_test.go
g10k_test.go
git.go
tests/TestConfigUseSSHAgent.yaml
tests/TestReadPuppetfileSSHKeyAlreadyLoaded

This parameter can be used to skip `ssh-add` commands before git over SSH commands, fixes #171

add module parameter :use_ssh_agent

---

forge.go
g10k.go
g10k_test.go
helper.go
puppetfile.go
tests/TestConfigStripComponentRegex.yaml
tests/TestConfigStripComponentString.yaml
tests/TestConfigStripComponentStringConflict.yaml

Replaces #202 (Still thank you @andni233) 
```
r10k supports a source configuration option strip_component: https://github.com/puppetlabs/r10k/blob/main/doc/dynamic-environments/configuration.mkd#strip_component
This adds similar support to g10k.
```

Add support for strip_component

---

README.md

Fix 'performance' typo in README

---

config.go

If the puppetfile does not contain `moduledir` config line then the default module directory is used even with `-moduledir` parameter being specified.

fix default moduledir not being overriden by moduledir parameter

---

g10k.go

Modules from puppet forge were being stored directly under cache directory instead of `forge` subdirectory in cache.
This was a difference in behaviour between `config` and `puppetfile` modes and causing forge modules to be stored 2x in cache.

cache forge modules under its own cache directory in puppetfile mode

---

build_release.sh

- fix build times
- build Darwin (MacOS) arm64 executables

Improve release process
